"""First migration

Revision ID: 1ade05e80cb7
Revises: 
Create Date: 2024-11-12 18:06:07.107155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ade05e80cb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('real_first_name', sa.String(), nullable=True),
    sa.Column('real_last_name', sa.String(), nullable=True),
    sa.Column('class_letter', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('achevements',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_subject', sa.String(), nullable=False),
    sa.Column('first_subject_group', sa.String(), nullable=False),
    sa.Column('first_subject_group_index', sa.Integer(), nullable=False),
    sa.Column('first_subject_first_grade', sa.Float(), nullable=False),
    sa.Column('first_subject_second_grade', sa.Float(), nullable=False),
    sa.Column('first_subject_exam_grade', sa.Integer(), nullable=False),
    sa.Column('second_subject', sa.String(), nullable=False),
    sa.Column('second_subject_group', sa.String(), nullable=False),
    sa.Column('second_subject_group_index', sa.Integer(), nullable=False),
    sa.Column('second_subject_first_grade', sa.Float(), nullable=False),
    sa.Column('second_subject_second_grade', sa.Float(), nullable=False),
    sa.Column('second_subject_exam_grade', sa.Integer(), nullable=False),
    sa.Column('olymp', sa.String(), nullable=False),
    sa.Column('olymp_grade', sa.Integer(), nullable=False),
    sa.Column('year_grade', sa.Float(), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achevements')
    op.drop_table('users')
    # ### end Alembic commands ###
